/**
 * Kibernetika project, backend component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KibernetikaProjectBackendComponent) {
      root.KibernetikaProjectBackendComponent = {};
    }
    root.KibernetikaProjectBackendComponent.DealerclientResourceLimit = factory(root.KibernetikaProjectBackendComponent.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DealerclientResourceLimit model module.
   * @module model/DealerclientResourceLimit
   * @version 0.2
   */

  /**
   * Constructs a new <code>DealerclientResourceLimit</code>.
   * @alias module:model/DealerclientResourceLimit
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>DealerclientResourceLimit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DealerclientResourceLimit} obj Optional instance to populate.
   * @return {module:model/DealerclientResourceLimit} The populated <code>DealerclientResourceLimit</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('replicas')) {
        obj['replicas'] = ApiClient.convertToType(data['replicas'], 'Number');
      }
      if (data.hasOwnProperty('execution_time')) {
        obj['execution_time'] = ApiClient.convertToType(data['execution_time'], 'Number');
      }
      if (data.hasOwnProperty('cpu_mi')) {
        obj['cpu_mi'] = ApiClient.convertToType(data['cpu_mi'], 'Number');
      }
      if (data.hasOwnProperty('parallel_runs')) {
        obj['parallel_runs'] = ApiClient.convertToType(data['parallel_runs'], 'Number');
      }
      if (data.hasOwnProperty('memory_mb')) {
        obj['memory_mb'] = ApiClient.convertToType(data['memory_mb'], 'Number');
      }
      if (data.hasOwnProperty('memory')) {
        obj['memory'] = ApiClient.convertToType(data['memory'], 'String');
      }
      if (data.hasOwnProperty('gpu')) {
        obj['gpu'] = ApiClient.convertToType(data['gpu'], 'Number');
      }
      if (data.hasOwnProperty('cpu')) {
        obj['cpu'] = ApiClient.convertToType(data['cpu'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} replicas
   */
  exports.prototype['replicas'] = undefined;
  /**
   * @member {Number} execution_time
   */
  exports.prototype['execution_time'] = undefined;
  /**
   * @member {Number} cpu_mi
   */
  exports.prototype['cpu_mi'] = undefined;
  /**
   * @member {Number} parallel_runs
   */
  exports.prototype['parallel_runs'] = undefined;
  /**
   * @member {Number} memory_mb
   */
  exports.prototype['memory_mb'] = undefined;
  /**
   * @member {String} memory
   */
  exports.prototype['memory'] = undefined;
  /**
   * @member {Number} gpu
   */
  exports.prototype['gpu'] = undefined;
  /**
   * @member {String} cpu
   */
  exports.prototype['cpu'] = undefined;



  return exports;
}));


