/**
 * Kibernetika project, backend component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KibernetikaProjectBackendComponent) {
      root.KibernetikaProjectBackendComponent = {};
    }
    root.KibernetikaProjectBackendComponent.MlappVolumeMount = factory(root.KibernetikaProjectBackendComponent.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MlappVolumeMount model module.
   * @module model/MlappVolumeMount
   * @version 0.2
   */

  /**
   * Constructs a new <code>MlappVolumeMount</code>.
   * @alias module:model/MlappVolumeMount
   * @class
   * @param name {String} 
   */
  var exports = function(name) {
    var _this = this;





    _this['name'] = name;
  };

  /**
   * Constructs a <code>MlappVolumeMount</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MlappVolumeMount} obj Optional instance to populate.
   * @return {module:model/MlappVolumeMount} The populated <code>MlappVolumeMount</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('subPath')) {
        obj['subPath'] = ApiClient.convertToType(data['subPath'], 'String');
      }
      if (data.hasOwnProperty('readOnly')) {
        obj['readOnly'] = ApiClient.convertToType(data['readOnly'], 'Boolean');
      }
      if (data.hasOwnProperty('mountPath')) {
        obj['mountPath'] = ApiClient.convertToType(data['mountPath'], 'String');
      }
      if (data.hasOwnProperty('gitRevision')) {
        obj['gitRevision'] = ApiClient.convertToType(data['gitRevision'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} subPath
   */
  exports.prototype['subPath'] = undefined;
  /**
   * @member {Boolean} readOnly
   */
  exports.prototype['readOnly'] = undefined;
  /**
   * @member {String} mountPath
   */
  exports.prototype['mountPath'] = undefined;
  /**
   * @member {String} gitRevision
   */
  exports.prototype['gitRevision'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;



  return exports;
}));


