/**
 * Kibernetika project, backend component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DealerclientResourceLimit', 'model/MlappResourceAccelerators'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DealerclientResourceLimit'), require('./MlappResourceAccelerators'));
  } else {
    // Browser globals (root is window)
    if (!root.KibernetikaProjectBackendComponent) {
      root.KibernetikaProjectBackendComponent = {};
    }
    root.KibernetikaProjectBackendComponent.MlappResourceRequest = factory(root.KibernetikaProjectBackendComponent.ApiClient, root.KibernetikaProjectBackendComponent.DealerclientResourceLimit, root.KibernetikaProjectBackendComponent.MlappResourceAccelerators);
  }
}(this, function(ApiClient, DealerclientResourceLimit, MlappResourceAccelerators) {
  'use strict';




  /**
   * The MlappResourceRequest model module.
   * @module model/MlappResourceRequest
   * @version 0.2
   */

  /**
   * Constructs a new <code>MlappResourceRequest</code>.
   * @alias module:model/MlappResourceRequest
   * @class
   * @param accelerators {module:model/MlappResourceAccelerators} 
   */
  var exports = function(accelerators) {
    var _this = this;

    _this['accelerators'] = accelerators;


  };

  /**
   * Constructs a <code>MlappResourceRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MlappResourceRequest} obj Optional instance to populate.
   * @return {module:model/MlappResourceRequest} The populated <code>MlappResourceRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accelerators')) {
        obj['accelerators'] = MlappResourceAccelerators.constructFromObject(data['accelerators']);
      }
      if (data.hasOwnProperty('requests')) {
        obj['requests'] = DealerclientResourceLimit.constructFromObject(data['requests']);
      }
      if (data.hasOwnProperty('limits')) {
        obj['limits'] = DealerclientResourceLimit.constructFromObject(data['limits']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/MlappResourceAccelerators} accelerators
   */
  exports.prototype['accelerators'] = undefined;
  /**
   * @member {module:model/DealerclientResourceLimit} requests
   */
  exports.prototype['requests'] = undefined;
  /**
   * @member {module:model/DealerclientResourceLimit} limits
   */
  exports.prototype['limits'] = undefined;



  return exports;
}));


