/**
 * Kibernetika project, backend component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KibernetikaProjectBackendComponent) {
      root.KibernetikaProjectBackendComponent = {};
    }
    root.KibernetikaProjectBackendComponent.MlappS3BucketSource = factory(root.KibernetikaProjectBackendComponent.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MlappS3BucketSource model module.
   * @module model/MlappS3BucketSource
   * @version 0.2
   */

  /**
   * Constructs a new <code>MlappS3BucketSource</code>.
   * @alias module:model/MlappS3BucketSource
   * @class
   * @param bucket {String} 
   */
  var exports = function(bucket) {
    var _this = this;



    _this['bucket'] = bucket;

  };

  /**
   * Constructs a <code>MlappS3BucketSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MlappS3BucketSource} obj Optional instance to populate.
   * @return {module:model/MlappS3BucketSource} The populated <code>MlappS3BucketSource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('region')) {
        obj['region'] = ApiClient.convertToType(data['region'], 'String');
      }
      if (data.hasOwnProperty('server')) {
        obj['server'] = ApiClient.convertToType(data['server'], 'String');
      }
      if (data.hasOwnProperty('bucket')) {
        obj['bucket'] = ApiClient.convertToType(data['bucket'], 'String');
      }
      if (data.hasOwnProperty('accountId')) {
        obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} region
   */
  exports.prototype['region'] = undefined;
  /**
   * @member {String} server
   */
  exports.prototype['server'] = undefined;
  /**
   * @member {String} bucket
   */
  exports.prototype['bucket'] = undefined;
  /**
   * @member {String} accountId
   */
  exports.prototype['accountId'] = undefined;



  return exports;
}));


