/**
 * Kibernetika project, backend component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KibernetikaProjectBackendComponent) {
      root.KibernetikaProjectBackendComponent = {};
    }
    root.KibernetikaProjectBackendComponent.MlappImages = factory(root.KibernetikaProjectBackendComponent.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MlappImages model module.
   * @module model/MlappImages
   * @version 0.2
   */

  /**
   * Constructs a new <code>MlappImages</code>.
   * @alias module:model/MlappImages
   * @class
   * @param gpu {String} 
   * @param cpu {String} 
   */
  var exports = function(gpu, cpu) {
    var _this = this;

    _this['gpu'] = gpu;
    _this['cpu'] = cpu;
  };

  /**
   * Constructs a <code>MlappImages</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MlappImages} obj Optional instance to populate.
   * @return {module:model/MlappImages} The populated <code>MlappImages</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('gpu')) {
        obj['gpu'] = ApiClient.convertToType(data['gpu'], 'String');
      }
      if (data.hasOwnProperty('cpu')) {
        obj['cpu'] = ApiClient.convertToType(data['cpu'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} gpu
   */
  exports.prototype['gpu'] = undefined;
  /**
   * @member {String} cpu
   */
  exports.prototype['cpu'] = undefined;



  return exports;
}));


