/**
 * Kibernetika project, backend component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KibernetikaProjectBackendComponent) {
      root.KibernetikaProjectBackendComponent = {};
    }
    root.KibernetikaProjectBackendComponent.MlappAutoscale = factory(root.KibernetikaProjectBackendComponent.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MlappAutoscale model module.
   * @module model/MlappAutoscale
   * @version 0.2
   */

  /**
   * Constructs a new <code>MlappAutoscale</code>.
   * @alias module:model/MlappAutoscale
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>MlappAutoscale</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MlappAutoscale} obj Optional instance to populate.
   * @return {module:model/MlappAutoscale} The populated <code>MlappAutoscale</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('target_average_utilization')) {
        obj['target_average_utilization'] = ApiClient.convertToType(data['target_average_utilization'], 'Number');
      }
      if (data.hasOwnProperty('min_replicas')) {
        obj['min_replicas'] = ApiClient.convertToType(data['min_replicas'], 'Number');
      }
      if (data.hasOwnProperty('enabled')) {
        obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
      }
      if (data.hasOwnProperty('max_replicas')) {
        obj['max_replicas'] = ApiClient.convertToType(data['max_replicas'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} target_average_utilization
   */
  exports.prototype['target_average_utilization'] = undefined;
  /**
   * @member {Number} min_replicas
   */
  exports.prototype['min_replicas'] = undefined;
  /**
   * @member {Boolean} enabled
   */
  exports.prototype['enabled'] = undefined;
  /**
   * @member {Number} max_replicas
   */
  exports.prototype['max_replicas'] = undefined;



  return exports;
}));


