/**
 * Kibernetika project, backend component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsTaskFormElement'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsTaskFormElement'));
  } else {
    // Browser globals (root is window)
    if (!root.KibernetikaProjectBackendComponent) {
      root.KibernetikaProjectBackendComponent = {};
    }
    root.KibernetikaProjectBackendComponent.ModelsInferenceVersion = factory(root.KibernetikaProjectBackendComponent.ApiClient, root.KibernetikaProjectBackendComponent.ModelsTaskFormElement);
  }
}(this, function(ApiClient, ModelsTaskFormElement) {
  'use strict';




  /**
   * The ModelsInferenceVersion model module.
   * @module model/ModelsInferenceVersion
   * @version 0.2
   */

  /**
   * Constructs a new <code>ModelsInferenceVersion</code>.
   * @alias module:model/ModelsInferenceVersion
   * @class
   * @param updated {String} 
   * @param form {Array.<module:model/ModelsTaskFormElement>} 
   * @param created {String} 
   * @param servingConfigTemplate {String} 
   * @param version {String} 
   * @param edgeConfigTemplate {String} 
   */
  var exports = function(updated, form, created, servingConfigTemplate, version, edgeConfigTemplate) {
    var _this = this;

    _this['Updated'] = updated;
    _this['Form'] = form;
    _this['Created'] = created;
    _this['ServingConfigTemplate'] = servingConfigTemplate;
    _this['Version'] = version;
    _this['EdgeConfigTemplate'] = edgeConfigTemplate;
  };

  /**
   * Constructs a <code>ModelsInferenceVersion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsInferenceVersion} obj Optional instance to populate.
   * @return {module:model/ModelsInferenceVersion} The populated <code>ModelsInferenceVersion</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Updated')) {
        obj['Updated'] = ApiClient.convertToType(data['Updated'], 'String');
      }
      if (data.hasOwnProperty('Form')) {
        obj['Form'] = ApiClient.convertToType(data['Form'], [ModelsTaskFormElement]);
      }
      if (data.hasOwnProperty('Created')) {
        obj['Created'] = ApiClient.convertToType(data['Created'], 'String');
      }
      if (data.hasOwnProperty('ServingConfigTemplate')) {
        obj['ServingConfigTemplate'] = ApiClient.convertToType(data['ServingConfigTemplate'], 'String');
      }
      if (data.hasOwnProperty('Version')) {
        obj['Version'] = ApiClient.convertToType(data['Version'], 'String');
      }
      if (data.hasOwnProperty('EdgeConfigTemplate')) {
        obj['EdgeConfigTemplate'] = ApiClient.convertToType(data['EdgeConfigTemplate'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} Updated
   */
  exports.prototype['Updated'] = undefined;
  /**
   * @member {Array.<module:model/ModelsTaskFormElement>} Form
   */
  exports.prototype['Form'] = undefined;
  /**
   * @member {String} Created
   */
  exports.prototype['Created'] = undefined;
  /**
   * @member {String} ServingConfigTemplate
   */
  exports.prototype['ServingConfigTemplate'] = undefined;
  /**
   * @member {String} Version
   */
  exports.prototype['Version'] = undefined;
  /**
   * @member {String} EdgeConfigTemplate
   */
  exports.prototype['EdgeConfigTemplate'] = undefined;



  return exports;
}));


