/**
 * Kibernetika project, backend component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsTaskFormElement', 'model/ModelsTaskFormElementValue'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsTaskFormElement'), require('./ModelsTaskFormElementValue'));
  } else {
    // Browser globals (root is window)
    if (!root.KibernetikaProjectBackendComponent) {
      root.KibernetikaProjectBackendComponent = {};
    }
    root.KibernetikaProjectBackendComponent.ModelsTaskFormElement = factory(root.KibernetikaProjectBackendComponent.ApiClient, root.KibernetikaProjectBackendComponent.ModelsTaskFormElement, root.KibernetikaProjectBackendComponent.ModelsTaskFormElementValue);
  }
}(this, function(ApiClient, ModelsTaskFormElement, ModelsTaskFormElementValue) {
  'use strict';




  /**
   * The ModelsTaskFormElement model module.
   * @module model/ModelsTaskFormElement
   * @version 0.2
   */

  /**
   * Constructs a new <code>ModelsTaskFormElement</code>.
   * @alias module:model/ModelsTaskFormElement
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>ModelsTaskFormElement</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsTaskFormElement} obj Optional instance to populate.
   * @return {module:model/ModelsTaskFormElement} The populated <code>ModelsTaskFormElement</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('elements')) {
        obj['elements'] = ApiClient.convertToType(data['elements'], [ModelsTaskFormElement]);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('required')) {
        obj['required'] = ApiClient.convertToType(data['required'], 'Boolean');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ModelsTaskFormElementValue.constructFromObject(data['value']);
      }
      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
      if (data.hasOwnProperty('width')) {
        obj['width'] = ApiClient.convertToType(data['width'], 'Number');
      }
      if (data.hasOwnProperty('listType')) {
        obj['listType'] = ApiClient.convertToType(data['listType'], 'String');
      }
      if (data.hasOwnProperty('hidden')) {
        obj['hidden'] = ApiClient.convertToType(data['hidden'], 'Boolean');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('options')) {
        obj['options'] = ApiClient.convertToType(data['options'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ModelsTaskFormElement>} elements
   */
  exports.prototype['elements'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Boolean} required
   */
  exports.prototype['required'] = undefined;
  /**
   * @member {module:model/ModelsTaskFormElementValue} value
   */
  exports.prototype['value'] = undefined;
  /**
   * @member {String} label
   */
  exports.prototype['label'] = undefined;
  /**
   * @member {Number} width
   */
  exports.prototype['width'] = undefined;
  /**
   * @member {String} listType
   */
  exports.prototype['listType'] = undefined;
  /**
   * @member {Boolean} hidden
   */
  exports.prototype['hidden'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Array.<String>} options
   */
  exports.prototype['options'] = undefined;



  return exports;
}));


