/**
 * Kibernetika project, backend component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/V1HostPathType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./V1HostPathType'));
  } else {
    // Browser globals (root is window)
    if (!root.KibernetikaProjectBackendComponent) {
      root.KibernetikaProjectBackendComponent = {};
    }
    root.KibernetikaProjectBackendComponent.V1HostPathVolumeSource = factory(root.KibernetikaProjectBackendComponent.ApiClient, root.KibernetikaProjectBackendComponent.V1HostPathType);
  }
}(this, function(ApiClient, V1HostPathType) {
  'use strict';




  /**
   * The V1HostPathVolumeSource model module.
   * @module model/V1HostPathVolumeSource
   * @version 0.2
   */

  /**
   * Constructs a new <code>V1HostPathVolumeSource</code>.
   * Represents a host path mapped into a pod. Host path volumes do not support ownership management or SELinux relabeling.
   * @alias module:model/V1HostPathVolumeSource
   * @class
   * @param path {String} Path of the directory on the host. If the path is a symlink, it will follow the link to the real path. More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath
   */
  var exports = function(path) {
    var _this = this;

    _this['path'] = path;

  };

  /**
   * Constructs a <code>V1HostPathVolumeSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1HostPathVolumeSource} obj Optional instance to populate.
   * @return {module:model/V1HostPathVolumeSource} The populated <code>V1HostPathVolumeSource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('path')) {
        obj['path'] = ApiClient.convertToType(data['path'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = V1HostPathType.constructFromObject(data['type']);
      }
    }
    return obj;
  }

  /**
   * Path of the directory on the host. If the path is a symlink, it will follow the link to the real path. More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath
   * @member {String} path
   */
  exports.prototype['path'] = undefined;
  /**
   * Type for HostPath Volume Defaults to \"\" More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath
   * @member {module:model/V1HostPathType} type
   */
  exports.prototype['type'] = undefined;



  return exports;
}));


